spring:
  config.activate.on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver

---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/foody
    driver-class-name: org.postgresql.Driver
    username: foody
    password: foody
