services:
  foody-db:
    image: postgres
    container_name: foody_postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/postgresql/conf.d:/etc/postgresql/conf.d
      - ./db/postgresql:/var/lib/postgresql
      - ./db/postgresql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=foody
      - POSTGRES_USER=foody
      - POSTGRES_PASSWORD=foody

networks:
  foody_network:
    driver: bridge
