## 고객 회원 가입 API
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "email": "customer@foody.io",
  "password": "password",
  "name": "홍길동",
  "nickname": "Red홍",
  "signUpType": "CUSTOMER"
}

###

## 사장님 회원 가입 API
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "email": "onwer@foody.io",
  "password": "password",
  "name": "백종원",
  "nickname": "100to1",
  "signUpType": "OWNER"
}

###


## 로그인 API
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "email": "customer@foody.io",
  "password": "password"
}
> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

###

## 회원 타입 조회 API
GET http://localhost:8080/auth/type
Content-Type: application/json

###
