### 메뉴 등록 API
POST http://localhost:8080/menus
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "shopId": "775ffe1e-9e72-44d6-a19d-c36bfbdb2aa3",
  "name": "돈까스",
  "price": 7000,
  "description": "든든한 돈까스를 드셔보세요",
  "menuStatus": "ON_SALE"
}


### 메뉴 전체 조회 API
GET http://localhost:8080/menus/775ffe1e-9e72-44d6-a19d-c36bfbdb2aa3?page=&size=3
Authorization: Bearer {{access_token}}

### 메뉴 단일 조회 API
GET http://localhost:8080/menus/menu/0bdcb8f8-cce3-4c81-918e-b630899efb4d
Authorization: Bearer {{access_token}}
