### 메뉴 등록 API
POST http://localhost:8080/menus
Content-Type: application/json

{
  "shopId": "9b12eb4d-3b7d-4bad-9bdd-2b0d7b3dcb6a",
  "name": "돈까스",
  "price": 7000,
  "description": "든든한 돈까스를 드셔보세요",
  "menuStatus": "ON_SALE"
}


### 메뉴 전체 조회 API
GET http://localhost:8080/menus/9b12eb4d-3b7d-4bad-9bdd-2b0d7b3dcb6a?page=&size=3
Authorization: Bearer {{access_token}}
