### Shop 생성 API
POST http://localhost:8080/shop/1
Content-Type: application/json

{
  "name": "마시도니",
  "phoneNumber": "02-941-3969",
  "description": "맛있는 제주흑돼지를 파는 마시도니입니다.",
  "address": "서울 성북구 길음동",
  "categoryIds": [
    "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"
  ],
  "regionId": "9b12eb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"
}

### Shop 전체 조회 API
GET http://localhost:8080/shop?page=0&size=2
Authorization: Bearer {{access_token}}

### Shop 단일 조회 API
GET http://localhost:8080/shop/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3acb4
Authorization: Bearer {{access_token}}

### Shop 검색 API
GET http://localhost:8080/shop/search?page=0&size=1
Authorization: Bearer {{access_token}}
